name: Event Reminder—Startup meeti

on:
  schedule:
    # This is in UTC time
    - cron: '1 9 29 4 *'
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Event Logs
        run: |
          echo "Event: Startup meeti, Description: Startup meeting, Event Time: 2025-04-29T14:32:00Z"
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Event Reminder: Startup meeti"
          body: |
            EVENT REMINDER
            ===============
            Event Name: Startup meeti
            Description: Startup meeting
            Event Time: 2025-04-29T14:32:00Z
          to: 22052939@kiit.ac.in
          from: Your GitHub Actions <souradipsaha2004@gmail.com>
