name: Event Reminder—Date with Ananya

on:
  schedule:
    # This is in UTC time
    - cron: '24 2 29 4 *'
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Event Logs
        run: |
          echo "Event: Date with Ananya, Description: Candle light dinner with Ananya, Event Time: 2025-04-29T02:25:00Z"
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Event Reminder: Date with Ananya"
          body: |
            EVENT REMINDER
            ===============
            Event Name: Date with Ananya
            Description: Candle light dinner with Ananya
            Event Time: 2025-04-29T02:25:00Z
          to: 22052939@kiit.ac.in
          from: Your GitHub Actions <souradipsaha2004@gmail.com>
